services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    ports:
      - "8012:8012"
    depends_on:
      - telegram-redis
    environment:
      - API_TOKEN=6874495766:AAGyocvfJ-DzaqDQfhMe7L7BeEzlG55S1lM
    volumes:
      - .:/app

  telegram-redis:
    image: "redis:alpine"
    container_name: telegram-redis
    ports:
      - "6379:6379"
