services:
  bot:
    build: .
    container_name: fastapi_telegram
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    
volumes:
  logs:
    driver: local
